### ISSUE TITLE
Add ehealthafrica as owner to npm package

### ISSUE THREAD

**Issue by gr2m** [eHealthAfrica/kazana-entities#5]
We use the [ehealthafrica](https://www.npmjs.com/~ehealthafrica) to publish all kazana packages. Can you add it as owner

```
npm onwer add ehealthafrica kazana-entities
```

Once that's done, you can set the according GH_TOKEN & NPM_TOKEN here https://travis-ci.org/eHealthAfrica/kazana-entities/settings

**Comment by karl-ehealth** [comment]
fixed
