### ISSUE TITLE
semantic release doesn't work

### ISSUE THREAD

**Issue by karlwestin** [eHealthAfrica/kazana-entities#8]
see the releases of 2.0.0 and 3.0.0 had to be forced with commits to master

**Comment by gr2m** [comment]
Can you add some more context to what is broken? I'm happy to help with that

**Comment by karl-ehealth** [comment]
this was when the PR was merged, and semantic-release decided not to release https://travis-ci.org/eHealthAfrica/kazana-entities/builds/92917916#L442

the commit you ref:ed in chat was an empty commit to trigger a release
https://travis-ci.org/eHealthAfrica/kazana-entities#L195

**Comment by gr2m** [comment]
Thanks! You indeed found a bug there, the `/` in the scope broke semantic-release :)

This will be fixed with https://github.com/semantic-release/commit-analyzer/pull/8

For the time begin, avoid using `/` in scopes. Sorry for the trouble

**Comment by karl-ehealth** [comment]
wow wow, good find!
